name: whisper

channels:
  - pytorch
  - defaults

dependencies:
  - cudatoolkit=11.3
  - git
  - numpy=1.22.3
  - pip=20.3
  - python=3.8.5
  - pytorch=1.11.0
  - scikit-image=0.19.2
  - torchvision=0.12.0
  - pip:
    - -r requirements.txt
